/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArtBall: typeof import('./components/ArtBall.vue')['default']
    ArtPlum: typeof import('./components/ArtPlum.vue')['default']
    ArtStar: typeof import('./components/ArtStar.vue')['default']
    BackgroundStar: typeof import('./components/BackgroundStar.vue')['default']
    Body: typeof import('./components/Body.vue')['default']
    CodePullOutbar: typeof import('./components/CodePullOutbar.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Home: typeof import('./components/Home.vue')['default']
    HomePullOutbar: typeof import('./components/HomePullOutbar.vue')['default']
    PullOut: typeof import('./c./components/HomePullOutbar.vue'default ']
    PullOutbar: typeof import('./components/PullOutbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Topbar: typeof import('./components/Topbar.vue')['default']
  }
}
